### ISSUE TITLE
Twitter Handle Is Listed As Missing when it is not

### ISSUE THREAD

**Issue by JoshuaHolme** [louisgrasset/touitomamout#140]
**Describe the bug**

Created the docker compose in unraid with the provided YAML file, but when it runs I get the following error.

```
touitomamout  | (node:8) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
touitomamout  | (Use `node --trace-warnings ...` to show where the warning was created)
touitomamout  | (node:8) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
touitomamout  | Error: 
touitomamout  | [touitomamout] Twitter username is missing.
touitomamout  |                └─ Please check 'TWITTER_HANDLE' in your .env settings.
touitomamout  |                └─ 🦣.
touitomamout  |     at file:///app/dist/configuration/configuration.js:21:23
touitomamout  |     at Array.forEach (<anonymous>)
touitomamout  |     at configuration (file:///app/dist/configuration/configuration.js:18:11)
touitomamout  |     at file:///app/dist/index.js:4:127
touitomamout  |     at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
touitomamout  |     at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
touitomamout  |     at async loadESM (node:internal/process/esm_loader:34:7)
touitomamout  |     at async handleMainPromise (node:internal/modules/run_main:66:12)
```

**To Reproduce**
1. Create an unraid compose docker with the following YAML
```
version: '3.9'

services:
  touitomamout:
    container_name: "touitomamout"
    image: louisgrasset/touitomamout:latest  # Or "ghcr.io/louisgrasset/touitomamout:latest"
    restart: unless-stopped
    environment:
      - ENV_FILE=.env
      - STORAGE_DIR=/data
    volumes:
      - ./data:/data
 ```
2. Add the `.env` file
```
TWITTER_HANDLE=HandleToBeMirrored
TWITTER_USERNAME=AuthenticatedHandle
TWITTER_PASSWORD=password
BLUESKY_INSTANCE=bsky.social
BLUESKY_IDENTIFIER=handle.bsky.social
BLUESKY_PASSWORD=AppPassword
SYNC_BLUESKY=true
SYNC_FREQUENCY_MIN=30
SYNC_PROFILE_DESCRIPTION=true
SYNC_PROFILE_PICTURE=true
SYNC_PROFILE_HEADER=true
SYNC_PROFILE_NAME=true
```
3. Start Docker

**Expected behavior**
The handle to be seen in the env file. Before I was getting an error that the .env file couldn't be found, now it finds the file but doesn't read the handle for some reason.

**Additional supporting information**
This same .env works if I run locally on my laptop, but if I run in docker (so it auto updates all the time) I get the provided error.
